spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csi?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties.hibernate.enable_lazy_load_no_trans: true